### ISSUE TITLE
Mouse Position With Dual Screen

### ISSUE THREAD

**Issue by hsayed21** [RaptorX/WindowSnipping#1]
**I face a problem with snipping with the second screen.
It's working perfect with the main screen size but, when I snipping something from the second screen it's not getting the right space that i selected**

**Comment by hsayed21** [comment]
@RaptorX

**Comment by hsayed21** [comment]
https://github.com/RaptorX/WindowSnipping/assets/47378309/8d820b4d-870f-4a5b-add2-7569892b4bdc

**Comment by RaptorX** [comment]
I was recently on a call with someone who had a similar issue, we will be updating the tool soon because now we know what was causing it.

can you do the following for me?
right click on the desktop and open your `Display Settings`. and tell me what your `Recomended` DPI settings percentage is:

![image](https://github.com/RaptorX/WindowSnipping/assets/328761/96fc6145-de7d-4c3a-9316-e011e296b478)

If your recommended in that monitor is not the `100%` scale then you are lucky and the issue will be resolved on the next update.

**Comment by hsayed21** [comment]
<img width="637" alt="image" src="https://github.com/RaptorX/WindowSnipping/assets/47378309/92b0895e-0de7-42ae-a0d1-66eef9d2f381">

**Comment by RaptorX** [comment]
Yup, that's the problem we identified and fixed. It will be released soon

**Comment by deanhouseholder** [comment]
I submitted this pull request to fix this issue which I was experiencing as well.
https://github.com/RaptorX/WindowSnipping/pull/3

**Comment by RaptorX** [comment]
Fixed by [1.57.14](https://github.com/RaptorX/WindowSnipping/releases/tag/v1.57.14)

**Comment by RaptorX** [comment]
Fixed by [1.57.14](https://github.com/RaptorX/WindowSnipping/releases/tag/v1.57.14)
