### ISSUE TITLE
Hotkey Settings screen font is too big since v1.57.14 release

### ISSUE THREAD

**Issue by deanhouseholder** [RaptorX/WindowSnipping#5]
The latest release caused the text font size on the Hotkey Settings screen to be too large to fit on the window.

![image](https://github.com/user-attachments/assets/6d23677a-1a8a-4067-b1c6-d9a37e23a02c)

**Comment by RaptorX** [comment]
We didnt make any changes to the font size on that release.

![image](https://github.com/user-attachments/assets/834e0fe3-1c1c-4ed0-8dd3-22e85a322ddc)


Verify that your Screen DPI settings are correct:

![image](https://github.com/user-attachments/assets/6151c5db-568a-423f-8f73-4ceb9863dfd2)

Changing this value might affect many scripts because handling DPI settings is not a simple process.

**Comment by deanhouseholder** [comment]
Ah. Yes. That was my issue. Thank you.
